@baseUrl = http://localhost:3333

### MESAS
POST {{baseUrl}}/mesas
Content-Type: application/json

{
  "numero": "3",
  "tipo": "mesa"
}

###

GET {{baseUrl}}/mesas


### PRODUTOS
POST {{baseUrl}}/produtos
Content-Type: application/json

{
  "nome": "pizza",
  "preco": 70
}

###

GET {{baseUrl}}/produtos


### PEDIDOS
POST {{baseUrl}}/pedidos
Content-Type: application/json

{
  "mesaComandaId": "31356542-86ec-43d0-b267-8998e784065d",
  "status": "aberto"
}

###

GET {{baseUrl}}/pedidos


### ITENS (mesma ideia: usa IDs dos GET acima)
POST {{baseUrl}}/itens
Content-Type: application/json

{
  "pedidoId": "9726e8d0-e596-4b8d-b573-12f4830c266d",
  "produtoId": "fa812849-9167-45f4-a679-f47b8be11cd5",
  "quantidade": 1,
  "observacoes": ""
}

###

GET {{baseUrl}}/itens


### USUÁRIOS
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
  "usuario": "guilherme",
  "senha": "123"
}

###

GET {{baseUrl}}/usuarios